// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart: typeof import('./components/Chart.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    FormModal: typeof import('./components/FormModal.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/Spinner.vue')['default']
    Terminal: typeof import('./components/Terminal.vue')['default']
  }
}
