app: fatapi
frameworkVersion: "3"
service: fatapi

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev

functions:
  fatapi:
    handler: app.handler
    url: true
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    

plugins:
  - serverless-python-requirements
  - serverless-dotenv
custom:
  pythonRequirements:
    layer: true
    slim: true
    zip: true
  
  dotenv:
    path: .env