<template>
<main col center pb-16 bg-gradient-to-b from-gray-200 via-gray-400 to-gray-600 h-full style="background: url(https://wallpapercave.com/wp/wp2062903.jpg); background-repeat: no-repeat; background-size: cover;">
    <div backdrop-blur-sm col center rounded-xl p-8>
    <h1 class="text-white underline drop-shadow-lg shadow-black m-2 text-center">Boilerplateless Applications powered by FastAPI, Prisma and VueJS </h1>
    <h2 class="text-lg text-cyan-400 drop-shadow-md shadow-black m-2 text-center">Forget about writing the same crud operations and setting up all the stuff, just focus on your schema and business logic. </h2>
    <h2 class="text-lg text-cyan-400 drop-shadow-md shadow-black m-2 text-center">All the CRUD operations and routes are autogenerated from your schema file, which you can edit directly on the GUI. </h2>
    <h2 class="text-lg text-cyan-400 drop-shadow-md shadow-black m-2 text-center">Get help from custom addons such as extended swagger ui, search engine, web terminal and monitoring dashboard for your app. </h2>
</div>
    <img src="/logo.svg" alt="logo" x16 mt-4 />
<v-footer app row center text-cyan-300 bg-black gap-4 py-2 px-8>
    2022 Developed by <a href="https://github.com/obahamonde" target="_blank" class="text-cyan-300 mx-8">Oscar Bahamonde</a>  Visit the Github Repo <a href="https://github.com/obahamonde/fastapi_app_builder" target="_blank" class="text-cyan-300"><Icon icon="mdi-github" color="cyan" x2 /></a>
</v-footer>
</main>
</template>