<template>
<main col center p-8 bg-gradient-to-b from-gray-200 via-gray-400 to-gray-600 h-full>
    <img src="/logo.svg" alt="logo" x16 />
    <h1 class="text-primary underline drop-shadow-lg shadow-black m-4 text-center">Boilerplateless Applications powered by FastAPI, Prisma and VueJS </h1>
    <h2 class="text-lg text-cyan-400 drop-shadow-md shadow-black m-4 text-center">Forget about writing the same crud operations and setting up all the stuff, just focus on your schema and business logic. </h2>
    <h2 class="text-lg text-cyan-400 drop-shadow-md shadow-black m-4 text-center">All the CRUD operations and routes are autogenerated from your schema file, which you can edit directly on the GUI. </h2>
    <h2 class="text-lg text-cyan-400 drop-shadow-md shadow-black m-4 text-center">Get help from custom addons such as extended swagger ui, search engine, web terminal and monitoring dashboard for your app. </h2>
</main>
</template>